### PR TITLE
Memory filter implementation/improvements

### PR DESCRIPTION
**Pull request by ssevertson**
Implement filters compatible with CouchDB for the Memory engine.

Based loosely on the old memory-filters branch, plus reading through the CouchDB view.js file to ensure compatibility.

Includes test cases.

### CODE REVIEW

**Comment by gorjuspixels** [comment]
Could this be committed to one of the newest branches? I have a production environment using couchdb - and it's all fine. But for testing we're using memory store and it fails every time when using filters.

**Comment by Fishrock123** [comment]
@jcrugzz @indexzero could this be looked at? Using filters is causing our tests to break, since they use memory.

I can confirm this pr allows to tests to work like they did before we implemented some filters.

**Comment by jcrugzz** [comment]
@Fishrock123 yea this does look good after closer inspection. Merging

**Comment by jcrugzz** [comment]
Published as `0.3.5`

**Comment by Fishrock123** [comment]
Thanks! :ship:

**Pull request merged**
